---

- name: install haproxy and socat
  apt: pkg={{ item }} state=latest
  with_items:
  - haproxy
  - socat

- name: enable haproxy
  lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
  notify: restart haproxy 

- name: deploy haproxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg force=yes
  notify: restart haproxy

- name: ensure public keys are added to authorized keys
  authorized_key: user=vagrant key="{{ lookup('file', '/vagrant/roles/mgmt/files/id_rsa.pub') }}"
